[package]
name = "grex_terminal_display"
version = "0.1.5"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
once_cell = "1.19.0"

[dependencies.bevy]
version = "0.13"

[dependencies.grex_framebuffer_extract]
git = "https://github.com/exvacuum/grex_framebuffer_extract"
tag = "v0.1.1"

[dependencies.grex_dither_post_process]
git = "https://github.com/exvacuum/grex_dither_post_process"
tag = "v0.1.3"

[dependencies.ratatui]
version = "0.26.2"
features = ["unstable-widget-ref"]

