[package]
name = "bevy_terminal_display"
version = "0.2.2"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
downcast-rs = "1.2.1"
once_cell = "1.19.0"

[dependencies.bevy]
version = "0.13"

[dependencies.bevy_framebuffer_extract]
git = "https://github.com/exvacuum/bevy_framebuffer_extract"
tag = "v0.1.2"

[dependencies.bevy_dither_post_process]
git = "https://github.com/exvacuum/bevy_dither_post_process"
tag = "v0.1.4"

[dependencies.ratatui]
version = "0.26.2"

