[package]
name = "bevy_terminal_display"
version = "0.3.0"
edition = "2021"
license = "0BSD OR MIT OR Apache-2.0"
description = "A plugin for the Bevy game engine which enables rendering to a terminal using unicode braille characters."

[dependencies]
crossbeam-channel = "0.5"
crossterm = "0.27"
downcast-rs = "1.2"
once_cell = "1.19"
bevy = "0.14"
bevy_headless_render = "0.1"
bevy_dither_post_process = "0.2"
ratatui = "0.26"

